version: 1.0
Resources:
  -TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "arn:aws:ecs:ap-south-1:610018615348:task-definition/authorization:1"
      LoadBalancerInfo:
        ContainerName: "authorization"
        ContainerPort: "8081"
      PlatformVersion: "Latest"
